### PR TITLE
Prevent secure information (private key & certs) from being written to disk

### PR DESCRIPTION
**Pull request by t0xicCode**
This commit makes it so that the certificate and the private keys are not written to disk during the extraction. They are passed around directly as objects. This is a more secure approach.

### CODE REVIEW

**Comment by floragunncom** [comment]
does this work for open ssl too? main reason for storing the certs and keys in that way is that this is (or was) the only way to get it working with open ssl)

**Comment by t0xicCode** [comment]
I'll have to take a quick look. Let me get back to you on that.

**Comment by t0xicCode** [comment]
@floragunncom Just ran the tests using netty-tcnative, and it all passed with flying colors, using OPENSSL as the provider for both the transports and http.

**Comment by floragunncom** [comment]
thx, will have a look

**Comment by floragunncom** [comment]
merged, thx a lot

**Pull request merged**
