### PR TITLE
Add local certs

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:

* Passes local certs along with peer certs for evaluating when additional context values
* Blocks: https://github.com/floragunncom/search-guard/pull/269

### CODE REVIEW

**Comment by floragunncom** [comment]
I started to integrate this PR into master. I changed a few minor things, you can see progress here:  https://github.com/floragunncom/search-guard-ssl/tree/jcantrill-add_local_certs

**Comment by floragunncom** [comment]
@jcantrill does this looks ok? https://github.com/floragunncom/search-guard-ssl/tree/jcantrill-add_local_certs

**Comment by jcantrill** [comment]
@floragunncom seems reasonable if you additinally require evaluating the principal

**Comment by floragunncom** [comment]
merged with https://github.com/floragunncom/search-guard-ssl/commit/8bbd0fff1186ddc93f8b333ea1065696e6a1d7ca

**Comment by floragunncom** [comment]
released with v20 today

**Pull request closed without merging**
